#
# GitHub Actions workflow for building and deploying my blog to AWS Lightsail.
#
# Author: Lucca Rodrigues
#
 
name: Build and deploy website

on: 
  push:
    branches: 
      # Main branch
      - main
      # Testing branch
      - test

jobs:

  # compile webpages 
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1    
      with:
        node-version: 14.x

    - name: Install dependencies
      run: npm ci

    - name: Compile Markdown files
      run: npm run content

    - name: Build Vue app
      run: npm run build

    - name: Create SSH identity file

      # Get BASE64-encoded private key stored in repo secret
      env:        
        DEPLOYMENTKEY: ${{ secrets.DEPLOYKEY }}

      # Decode with BASE64, change permissions with chmod        
      run: | 
        echo "$DEPLOYMENTKEY" | base64 --decode  >deployment.key
        chmod 400 deployment.key

    # Rsync over SSH
    - name: Deploy to AWS

      # transfer files with SSH key
      run: |
        rsync -zaPv -e "ssh -v -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i deployment.key" --delete ./dist/* ubuntu@34.200.98.64:/home/ubuntu/dist/      
        ssh -v -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i deployment.key ubuntu@34.200.98.64 './sync2.sh'  