name: Deploy website

on: 
  push:
    branches: [ main, test ]


jobs:
  deploy-website:

    runs-on: ubuntu-latest

    steps:

    # Check out code
    - uses: actions/checkout@v2

    # SSH private key stuff
    - name: Create identity file
      env:
        DEPLOYMENTKEY: ${{ secrets.DEPLOYKEY }}
      run: |
        echo "$DEPLOYMENTKEY" | base64 --decode  >deployment.key
        chmod 400 deployment.key

    # SSH into AWS Lightsail
    - name: SSH login
      run: |
        ssh -v -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i deployment.key ubuntu@34.200.98.64 /home/ubuntu/Personal-website/update.sh
        

    