name: Deploy website

on: 
  push:
    branches: [ main, test ]


jobs:
  test-secret:
    runs-on: ubuntu-latest

    steps:

    # Check out code
    - uses: actions/checkout@v2

    - name: Access secret
      env:
        COOL_SECRET: ${{ secrets.NOT_AN_IMPORTANT_SECRET }}
      run: 
        echo "$COOL_SECRET"