name: Build Website pages

on: 
  push:
    branches: [ main, test ]

jobs:
  build-website:

    runs-on: ubuntu-latest

    steps:

    # Check out code
    - uses: actions/checkout@v2

    # Node.js setup
    - name: Setting up Node.js!
      uses: actions/setup-node@v1    
      with:
        node-version: 14.x

    # Make sure we set up Node.js properly
    - name: Check Node.js version
      run: node --version

    # Install packages with NPM
    - name: Install dependencies
      run: npm ci

    # Compile webpages
    - name: Compile all webpages
      run: node compiler.js 34.200.98.64:3000

    # Check that there are indeed changes
    - name: Log file changes
      run: git status

    # Stage all changes
    - name: Stage all files
      run: git add .

    # User Config
    - name: Git config
      run: | 
        git config --global user.name 'ChromeUniverse' 
        git config --global user.email '33258966+ChromeUniverse@users.noreply.github.com'
    
    # Commit changes
    - name: Commit changes
      run: git commit -m "* Automated webpage compilation *"

    # Push changes to remote
    - name: Push changes
      run: git push origin test
        

    